AWSTemplateFormatVersion: 2010-09-09

Resources:
  AlbLogginFluentdTestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Logging-fluentd-test-Alb-SG
      GroupDescription: Alb security group
      VpcId: vpc-cf7068a9
      SecurityGroupIngress:
        - Description: Traffic from outside to port 80
          FromPort: 80
          IpProtocol: "tcp"
          CidrIp: 0.0.0.0/0
          ToPort: 80
      Tags:
        - Key: Name
          Value: Alb-SG

  LogginFluentdTestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Logging-fluentd-test-SG
      GroupDescription: Logging-fluentd-test security group
      SecurityGroupIngress:
        - Description: Traffic from ALB
          FromPort: 80
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref AlbLogginFluentdTestSG
          ToPort: 80
      VpcId: vpc-cf7068a9
      Tags:
        - Key: Name
          Value: LogginFluentdTestSG
  
  EcsHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the ECS hosts that run containers
      VpcId: vpc-cf7068a9
  
  EcsSecurityGroupIngressFromPublicALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from the public ALB
      GroupId: !Ref 'EcsHostSecurityGroup'
      IpProtocol: "-1"
      SourceSecurityGroupId: !Ref 'AlbLogginFluentdTestSG'
  
  EcsSecurityGroupIngressFromSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from other hosts in the same security group
      GroupId: !Ref 'EcsHostSecurityGroup'
      IpProtocol: "-1"
      SourceSecurityGroupId: !Ref 'EcsHostSecurityGroup'

  # ElasticSearchSGEgress:
  #   Type: "AWS::EC2::SecurityGroupIngress"
  #   Properties:
  #     GroupId:
  #       Fn::ImportValue: !Sub ${Environment}-infrastructure-logs-SG-ES
  #     IpProtocol: tcp
  #     FromPort: 443
  #     ToPort: 443
  #     SourceSecurityGroupId: !Ref LogginFluentdTestSG

  #Delete when network awsvpc
  # ElasticSearchSGEgressDefault:
  #   Type: "AWS::EC2::SecurityGroupIngress"
  #   Properties:
  #     GroupId:
  #       Fn::ImportValue: !Sub ${Environment}-infrastructure-logs-SG-ES
  #     IpProtocol: tcp
  #     FromPort: 443
  #     ToPort: 443
  #     SourceSecurityGroupId:
  #       Fn::ImportValue: !Sub ${Environment}-infrastructure-ecs-SG-MainEcsClusterSG

Outputs:
  AlbLogginFluentdTestSG:
    Description: LoggingFluentdTest ALB security group
    Value: !Ref AlbLogginFluentdTestSG
    Export:
      Name: AlbLogginFluentdTestSG

  LogginFluentdTestSG:
    Description: LoggingFluentdTest security group
    Value: !Ref LogginFluentdTestSG
    Export:
      Name: LogginFluentdTestSG

  EcsHostSecurityGroup:
    Description: EcsHostSecurityGroup security group
    Value: !Ref EcsHostSecurityGroup
    Export:
      Name: EcsHostSecurityGroup