AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  MinPolicyPercent:
      Type: Number
      Default: 100

  MaxPolicyPercent:
    Type: Number
    Default: 200

  CpuUnits:
    Type: String
    Default: 512

  MemoryUnits:
    Type: String
    Default: 512

  DesiredTask:
    Type: Number
    Default: 1

Resources:

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: Testing-Env-Cluster
      ServiceName: LoggingFluentdTest
      PlacementStrategies:
        - Type: binpack
          Field: cpu
      DeploymentConfiguration:
        MinimumHealthyPercent: !Ref MinPolicyPercent
        MaximumPercent: !Ref MaxPolicyPercent
      DesiredCount: !Ref DesiredTask
      TaskDefinition: !Ref Task
      LoadBalancers:
        - ContainerName: web-server
          ContainerPort: 80
          TargetGroupArn:
            Fn::ImportValue: TargetGroupLogginFluentdTest
   
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Memory: !Ref MemoryUnits
      Cpu: !Ref CpuUnits
      TaskRoleArn:
        Fn::ImportValue: LogginFluentdTestRole-ARN
      ExecutionRoleArn:
        Fn::ImportValue: LogginFluentdTestRole-ARN
      ContainerDefinitions:
        - Name: web-server
          Image: httpd
          Essential: true
          
          LogConfiguration:
              LogDriver: awsfirelens
              Options:
                Name: forward
                Host: fluentdhost_el_que_sea
                Port: "24224"

          PortMappings:
            - ContainerPort: 80
          # Command:
          #   - sleep 1000 # ESTO HAY QUE MIRARLO
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -s --fail "http://localhost/"
            StartPeriod: 120

        - Name: log_router
          ## 906394416424.dkr.ecr.eu-west-1.amazonaws.com/aws-for-fluent-bit:latest  Esta es la imágen recomendada para AWS
          Image: "amazon/aws-for-fluent-bit:latest"  
          Essential: true
          
          FirelensConfiguration:
            Type: "fluentbit"
            # Options: 
            #   config-file-type: file  #puede ser s3 
            #   config-file-value: "URL del archivo de configuración (dentro de la imágen)" # "arn:aws:s3:::yourbucket/yourdirectory/extra.conf" #Usar un bucket que exista y el extra.conf está en el repo de FireLens
          
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: firelens-container
              awslogs-region: eu-west-1
              awslogs-create-group: "true"
              awslogs-stream-prefix: firelens

          VolumesFrom:
            - SourceContainer: web-server  
 
Outputs:
  Service:
    Description: ECS Service Arn for Logging Fluentd Test
    Value: !Ref Service
    Export:
      Name: Service

  Task:
    Description: Logging Fluentd Test TargetGroup Arn
    Value: !Ref Task
    Export:
      Name: TaskDefinition
